"""add destination gallery and neighbourhoods

Revision ID: c6ea02d5caec
Revises: b01d8b4f27a0
Create Date: 2026-07-12 18:22:33.075666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6ea02d5caec'
down_revision: Union[str, Sequence[str], None] = 'b01d8b4f27a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "destinations",
        sa.Column(
            "gallery",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    op.add_column(
        "destinations",
        sa.Column(
            "neighbourhoods",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'neighbourhoods')
    op.drop_column('destinations', 'gallery')
    # ### end Alembic commands ###
